#pragma once

#define OBJ_PICKING_NONE -1


#define TILE_OBJ_COUNT 19
#define TOKEN_OBJ_COUNT_TOTAL 6


#define OBS_TOKEN_FIRST_ARRANGE 0
#define OBS_TOKEN_ENABLE_INDICATOR_RED 1
#define OBS_TOKEN_ENABLE_INDICATOR_GREEN 2
#define OBS_TOKEN_MOVE 3
#define OBS_TOKEN_DISABLE_INDICATOR 4
#define OBS_TILE_FIRST_ARRANGE 5
#define OBS_TILE_POS_IMPOSSIBLE 6
#define OBS_TILE_POS_POSSIBLE 7
#define OBS_TILE_MOVE 8