#pragma once

enum {
	ID_COMMAND_REALTIME_UPDATE,
	ID_CONTROL_MAIN_VISUAL,
	ID_CONTROL_MAIN_PLAY,
	ID_CONTROL_RESOLUTION_1,
	ID_CONTROL_RESOLUTION_2,
	ID_CONTROL_RESOLUTION_4,
	ID_CONTROL_RESOLUTION_8,
	ID_CONTROL_RESOLUTION_16,
};