#pragma once

enum {
	ID_COMMAND_REALTIME_UPDATE=9999,
	ID_CONTROL_TRANSPARENCY,
	ID_CONTROL_TRANSPARENCY_NORMAL,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_1,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_2,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_3,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_4,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_5,
	ID_CONTROL_TRANSPARENCY_DEPTH_PEEL_6
};