#pragma once

#define BINDING_MATERIAL_TEX_MAX 10

#define SHADER_REG_CB_WORLD 0
#define SHADER_REG_CB_VIEW 1
#define SHADER_REG_CB_PROJ 2
#define SHADER_REG_CB_LIGHT_DIRECTIONAL 3
#define SHADER_REG_CB_LIGHT_POINT 4
#define SHADER_REG_CB_LIGHT_SPOT 5
#define SHADER_REG_CB_EYE 6

#define SHADER_REG_SRV_CM 0
#define SHADER_REG_SRV_DCM 1
#define SHADER_REG_SRV_TEX 10
#define SHADER_REG_SRV_SSAO 20
#define SHADER_REG_SRV_SHADOW 21
#define SHADER_REG_SRV_SHADOW_TRANSP 22
#define SHADER_REG_SRV_DISPLACE 23
#define SHADER_REG_SRV_ROUGHNESS 24
#define SHADER_REG_SRV_METALLIC 25
#define SHADER_REG_SRV_DEPTH 26

#define SHADER_REG_SAMP_POINT 0
#define SHADER_REG_SAMP_LINEAR 1
#define SHADER_REG_SAMP_LINEAR_POINT 3
#define SHADER_REG_SAMP_ANISOTROPIC 4
#define SHADER_REG_SAMP_CMP_POINT 5
#define SHADER_REG_SAMP_CMP_LINEAR_POINT 6